# Generated by Django 3.0.7 on 2020-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('id_card', models.CharField(max_length=20)),
                ('balance', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('maze_games_count', models.IntegerField(default=0)),
                ('maze_score_day', models.IntegerField(default=0)),
                ('maze_score_all_time', models.IntegerField(default=0)),
            ],
        ),
    ]
